spring:
  application:
    name: subscribe-center-sample

server:
  port: 8100

logging:
  level:
    root: INFO
    com.wly.center: DEBUG

subscribe-center:
  port: 8300
  baseAdminUrl: http://localhost:8200
  renewIntervalSeconds: 10
  registerName: ${spring.application.name}
  adminServiceName: subscribe-center-server
  discoveryAddresses:
    - http://localhost:8200
    - http://localhost:8201
  refreshClusterIntervalSeconds: 2
  healthCheckIntervalSeconds: 1
