spring:
  application:
    name: subscribe-center-server
  datasource:
    url: jdbc:mysql://localhost:3306/sub_center?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: lifan1994

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8201

logging:
  level:
    root: INFO
    com.wly.center: DEBUG

master:
  ha:
    select:
      enable: true
      renewInterval: 1